eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8761
management:
  context-path:  /